export const coursesData = [
  {
    id: 1,
    title: "GATE 2025 Complete Course - Mechanical Engineering",
    description: "Comprehensive preparation for GATE Mechanical with live classes, doubt support, and mock tests",
    image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?q=80&w=2940&auto=format&fit=crop",
    category: "GATE",
    subcategory: "Mechanical",
    level: "Advanced",
    duration: "6 months",
    language: "English",
    instructor: {
      name: "Dr. Rajesh Kumar",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2940&auto=format&fit=crop",
      rating: 4.8,
    },
    pricing: {
      current: 12999,
      original: 24999,
      discount: 48,
    },
    stats: {
      students: 5240,
      hours: 120,
      rating: 4.8,
      reviews: 1250,
      successRate: 92,
    },
    features: ["Live Classes", "Doubt Support", "Mock Tests", "Study Material"],
    badge: "Bestseller",
    isNew: false,
    isFree: false,
  },
  {
    id: 2,
    title: "IAS Foundation 2025 - Complete UPSC Preparation",
    description: "Complete UPSC preparation with current affairs, mock tests, essay writing, and interview guidance",
    image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=2940&auto=format&fit=crop",
    category: "IAS",
    subcategory: "General Studies",
    level: "Intermediate",
    duration: "12 months",
    language: "Hindi",
    instructor: {
      name: "Prof. Anita Sharma",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?q=80&w=2940&auto=format&fit=crop",
      rating: 4.9,
    },
    pricing: {
      current: 18999,
      original: 35999,
      discount: 47,
    },
    stats: {
      students: 3180,
      hours: 200,
      rating: 4.9,
      reviews: 890,
      successRate: 78,
    },
    features: ["Current Affairs", "Mock Tests", "Essay Writing", "Interview Prep"],
    badge: "New Launch",
    isNew: true,
    isFree: false,
  },
  {
    id: 3,
    title: "Class 12 Physics Mastery - JEE/NEET Preparation",
    description: "Complete CBSE Physics with JEE/NEET preparation and practical sessions",
    image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=2940&auto=format&fit=crop",
    category: "Class 12",
    subcategory: "Physics",
    level: "Intermediate",
    duration: "4 months",
    language: "English",
    instructor: {
      name: "Dr. Vikram Singh",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
      rating: 4.7,
    },
    pricing: {
      current: 8999,
      original: 15999,
      discount: 44,
    },
    stats: {
      students: 8450,
      hours: 80,
      rating: 4.7,
      reviews: 2100,
      successRate: 95,
    },
    features: ["Practical Sessions", "JEE Prep", "NEET Prep", "Concept Videos"],
    badge: "Popular",
    isNew: false,
    isFree: false,
  },
  {
    id: 4,
    title: "ESE Mechanical 2025 - Engineering Services Exam",
    description: "Complete ESE preparation for Mechanical branch with mock tests and interview guidance",
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?q=80&w=2940&auto=format&fit=crop",
    category: "ESE",
    subcategory: "Mechanical",
    level: "Advanced",
    duration: "8 months",
    language: "English",
    instructor: {
      name: "Er. Suresh Patel",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2940&auto=format&fit=crop",
      rating: 4.6,
    },
    pricing: {
      current: 15999,
      original: 28999,
      discount: 45,
    },
    stats: {
      students: 2890,
      hours: 150,
      rating: 4.6,
      reviews: 650,
      successRate: 82,
    },
    features: ["Mock Tests", "Interview Prep", "Previous Papers", "Doubt Support"],
    badge: "Limited Seats",
    isNew: false,
    isFree: false,
  },
  {
    id: 5,
    title: "Class 10 Mathematics Foundation",
    description: "Complete CBSE Mathematics with board exam preparation and concept clarity",
    image: "https://images.unsplash.com/photo-1596495578065-6e0763fa1178?q=80&w=2940&auto=format&fit=crop",
    category: "Class 10",
    subcategory: "Mathematics",
    level: "Beginner",
    duration: "3 months",
    language: "Hindi",
    instructor: {
      name: "Prof. Ramesh Gupta",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
      rating: 4.8,
    },
    pricing: {
      current: 5999,
      original: 9999,
      discount: 40,
    },
    stats: {
      students: 12340,
      hours: 60,
      rating: 4.8,
      reviews: 3200,
      successRate: 97,
    },
    features: ["Board Exam Prep", "Concept Videos", "Practice Tests", "Doubt Support"],
    badge: "Foundation",
    isNew: false,
    isFree: false,
  },
  {
    id: 6,
    title: "GATE Computer Science 2025",
    description: "Complete CS preparation with coding practice, algorithms, and system design",
    image: "https://images.unsplash.com/photo-1532012197267-da84d127e765?q=80&w=2940&auto=format&fit=crop",
    category: "GATE",
    subcategory: "Computer Science",
    level: "Advanced",
    duration: "6 months",
    language: "English",
    instructor: {
      name: "Dr. Amit Verma",
      image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2940&auto=format&fit=crop",
      rating: 4.9,
    },
    pricing: {
      current: 14999,
      original: 26999,
      discount: 44,
    },
    stats: {
      students: 7650,
      hours: 140,
      rating: 4.9,
      reviews: 1800,
      successRate: 89,
    },
    features: ["Coding Practice", "Algorithms", "System Design", "Mock Tests"],
    badge: "Trending",
    isNew: false,
    isFree: false,
  },
  {
    id: 7,
    title: "Free Introduction to Programming",
    description: "Learn programming basics with Python - completely free course for beginners",
    image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2940&auto=format&fit=crop",
    category: "Programming",
    subcategory: "Python",
    level: "Beginner",
    duration: "2 months",
    language: "English",
    instructor: {
      name: "Prof. Sarah Johnson",
      image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?q=80&w=2940&auto=format&fit=crop",
      rating: 4.5,
    },
    pricing: {
      current: 0,
      original: 0,
      discount: 0,
    },
    stats: {
      students: 15000,
      hours: 40,
      rating: 4.5,
      reviews: 4500,
      successRate: 85,
    },
    features: ["Hands-on Projects", "Code Practice", "Certificates", "Community Support"],
    badge: "Free",
    isNew: false,
    isFree: true,
  },
  {
    id: 8,
    title: "JEE Main 2025 Mathematics",
    description: "Complete JEE Main Mathematics preparation with advanced problem solving",
    image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2940&auto=format&fit=crop",
    category: "JEE",
    subcategory: "Mathematics",
    level: "Advanced",
    duration: "5 months",
    language: "Hindi",
    instructor: {
      name: "Prof. Anil Sharma",
      image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
      rating: 4.7,
    },
    pricing: {
      current: 11999,
      original: 19999,
      discount: 40,
    },
    stats: {
      students: 9500,
      hours: 100,
      rating: 4.7,
      reviews: 2300,
      successRate: 88,
    },
    features: ["Problem Solving", "Mock Tests", "Previous Papers", "Doubt Sessions"],
    badge: "Hot",
    isNew: true,
    isFree: false,
  },
]

export const filterOptions = {
  categories: ["All", "GATE", "IAS", "Class 12", "Class 10", "ESE", "JEE", "Programming"],
  subcategories: {
    GATE: ["Mechanical", "Computer Science", "Electrical", "Civil"],
    IAS: ["General Studies", "Optional Subjects", "Interview Prep"],
    "Class 12": ["Physics", "Chemistry", "Mathematics", "Biology"],
    "Class 10": ["Mathematics", "Science", "Social Science"],
    ESE: ["Mechanical", "Electrical", "Civil"],
    JEE: ["Physics", "Chemistry", "Mathematics"],
    Programming: ["Python", "JavaScript", "Java", "C++"],
  },
  levels: ["All", "Beginner", "Intermediate", "Advanced"],
  languages: ["All", "English", "Hindi"],
  pricing: ["All", "Free", "Paid", "Under ₹10,000", "₹10,000 - ₹20,000", "Above ₹20,000"],
  duration: ["All", "1-3 months", "3-6 months", "6-12 months", "12+ months"],
  features: ["Live Classes", "Doubt Support", "Mock Tests", "Study Material", "Interview Prep"],
}

export const sortOptions = [
  { value: "popularity", label: "Most Popular" },
  { value: "rating", label: "Highest Rated" },
  { value: "price-low", label: "Price: Low to High" },
  { value: "price-high", label: "Price: High to Low" },
  { value: "newest", label: "Newest First" },
  { value: "students", label: "Most Enrolled" },
]
