const apiConstants = {
    BACKEND_API_BASE_URL: "http://localhost:5000/api/v1",
    TOKEN_KEY: "userToken",
    auth: {
        BASE_ROUTE: "/auth",
        LOGIN: "/auth/login",
        REGISTER: "/auth/register",
        FORGOT_PASSWORD: "/auth/forgot-password",
        VALIDATE_PASSWORD_RESET_LINK: "/validate-reset-link",
        RESET_PASSWORD: "/auth/change-password",
        CURRENT_USER: "/auth/current-user",
        LOGOUT: "/auth/logout",
        AUTHENTICATE: "/authenticate",
    },
    course: {
        BASE_ROUTE: "/course",
        CREATE_COURSE: "/",
        COURSE_LIST: "/",
        UPDATE_COURSE: "/",
        GET_COURSE_DETAILS: "/",
        DELETE_COURSE: "/",
        GET_COURSE_STATS: "/get-permission-stats",
    },
    module: {
        BASE_ROUTE: "/course",
        MODULE_LIST: "/",
        GET_MODULE_DETAILS: "/",
        GET_MODULE_STATS: "/stats",
    },
    lesson: {
        BASE_ROUTE: "/course",
        LESSON_LIST: "/",
        GET_LESSON_DETAILS: "/",
        GET_LESSON_STATS: "/stats",
    },
    video: {
        BASE_ROUTE: "/course",
        VIDEO_LIST: "/",
        GET_VIDEO_DETAILS: "/",
        GET_VIDEO_STATS: "/stats",
    },
    users: {
        BASE_ROUTE: "/users",
        CREATE_USERS: "/",
        USERS_LIST: "/",
        UPDATE_USERS: "/",
        GET_USERS_DETAILS: "/",
        DELETE_USERS: "/",
        GET_USERS_STATS: "/get-users-stats",
    },
    loadingStateKeys: {
        GET_COURSE_DETAILS: "getCourseDetails",
        GET_COURSE_STATS: "getCourseStats",
        GET_COURSE_LIST: "getCourseList",

        GET_MODULE_DETAILS: "getMODULEDetails",
        GET_MODULE_STATS: "getMODULEStats",
        GET_MODULE_LIST: "getMODULEList",

        GET_LESSON_DETAILS: "getLESSONDetails",
        GET_LESSON_STATS: "getLESSONStats",
        GET_LESSON_LIST: "getLESSONList",

        GET_VIDEO_DETAILS: "getVIDEODetails",
        GET_VIDEO_STATS: "getVIDEOStats",
        GET_VIDEO_LIST: "getVIDEOList",

        CREATE_USERS: "createUsers",
        UPDATE_USERS: "updateUsers",
        GET_USERS_DETAILS: "getUsersDetails",
        GET_USERS_STATS: "getUsersStats",
        DELETE_USERS: "deleteUsers",
        GET_USERS_LIST: "getUsersList",

        SIGN_UP: "signup",
        VERIFY_EMAIL: "verifyEmail",
        SETUP_BASE_INFO: "setupBaseInfo",
        SETUP_PAYMENT: "setupPayment",
        SETUP_DETAILS: "setupDetails",
        SETUP_TEMPLATE: "setupTemplate",
        SETUP_PASSWORD: "setupPassword",
        FILE_UPLOAD_KEY: "fileUpload",
        CURRENT_ONBOARDED_USER: "currentOnboardedUser",
        GET_TEMPLATE_LIST: "getTemplateList",

        AUTHENTICATE: "authenticate",
    },
    theme: {
        LIGHT: "light",
        DARK: "dark",
    },
};
export default apiConstants;
