export const testSeriesData = [
    {
        id: 1,
        title: "GATE 2025 Mock Test Series - Mechanical Engineering",
        description: "Complete mock test series with 50+ tests, detailed solutions, and performance analysis",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=2940&auto=format&fit=crop",
        category: "GATE",
        subcategory: "Mechanical",
        level: "Advanced",
        totalTests: 52,
        duration: "3 hours per test",
        language: "English",
        instructor: {
            name: "Dr. Rajesh Kumar",
            image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2940&auto=format&fit=crop",
            rating: 4.8,
        },
        pricing: {
            current: 2999,
            original: 4999,
            discount: 40,
        },
        stats: {
            students: 8240,
            rating: 4.8,
            reviews: 1850,
            accuracy: 95,
        },
        features: ["Detailed Solutions", "Performance Analytics", "All India Rank", "Previous Year Papers"],
        badge: "Bestseller",
        isNew: false,
        isFree: false,
        testTypes: ["Full Length", "Subject Wise", "Previous Year"],
    },
    {
        id: 2,
        title: "IAS Prelims 2025 Test Series",
        description: "Comprehensive test series for IAS Prelims with current affairs and GS coverage",
        image: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?q=80&w=2940&auto=format&fit=crop",
        category: "IAS",
        subcategory: "Prelims",
        level: "Intermediate",
        totalTests: 40,
        duration: "2 hours per test",
        language: "Hindi",
        instructor: {
            name: "Prof. Anita Sharma",
            image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?q=80&w=2940&auto=format&fit=crop",
            rating: 4.9,
        },
        pricing: {
            current: 3999,
            original: 6999,
            discount: 43,
        },
        stats: {
            students: 5180,
            rating: 4.9,
            reviews: 1200,
            accuracy: 92,
        },
        features: ["Current Affairs", "Detailed Explanations", "Performance Tracking", "Mobile App"],
        badge: "New Launch",
        isNew: true,
        isFree: false,
        testTypes: ["Full Length", "Subject Wise", "Current Affairs"],
    },
    {
        id: 3,
        title: "JEE Main 2025 Mock Tests",
        description: "Complete JEE Main preparation with chapter-wise and full-length mock tests",
        image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=2940&auto=format&fit=crop",
        category: "JEE",
        subcategory: "Main",
        level: "Advanced",
        totalTests: 45,
        duration: "3 hours per test",
        language: "English",
        instructor: {
            name: "Prof. Anil Sharma",
            image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
            rating: 4.7,
        },
        pricing: {
            current: 1999,
            original: 3499,
            discount: 43,
        },
        stats: {
            students: 12500,
            rating: 4.7,
            reviews: 3200,
            accuracy: 94,
        },
        features: ["Chapter Wise Tests", "Full Length Mocks", "Detailed Analysis", "Video Solutions"],
        badge: "Popular",
        isNew: false,
        isFree: false,
        testTypes: ["Full Length", "Chapter Wise", "Subject Wise"],
    },
    {
        id: 4,
        title: "NEET 2025 Mock Test Series",
        description: "Complete NEET preparation with biology, chemistry, and physics mock tests",
        image: "https://images.unsplash.com/photo-1559757148-5c350d0d3c56?q=80&w=2940&auto=format&fit=crop",
        category: "NEET",
        subcategory: "Medical",
        level: "Advanced",
        totalTests: 38,
        duration: "3 hours per test",
        language: "English",
        instructor: {
            name: "Dr. Priya Patel",
            image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?q=80&w=2940&auto=format&fit=crop",
            rating: 4.8,
        },
        pricing: {
            current: 2499,
            original: 4299,
            discount: 42,
        },
        stats: {
            students: 9800,
            rating: 4.8,
            reviews: 2100,
            accuracy: 96,
        },
        features: ["Subject Wise Tests", "NCERT Based", "Detailed Solutions", "Performance Reports"],
        badge: "Trending",
        isNew: false,
        isFree: false,
        testTypes: ["Full Length", "Subject Wise", "NCERT Based"],
    },
    {
        id: 5,
        title: "Class 12 Board Exam Practice Tests",
        description: "Complete board exam preparation with subject-wise mock tests and sample papers",
        image: "https://images.unsplash.com/photo-1503676260728-1c00da094a0b?q=80&w=2940&auto=format&fit=crop",
        category: "Class 12",
        subcategory: "Board Exams",
        level: "Intermediate",
        totalTests: 25,
        duration: "3 hours per test",
        language: "Hindi",
        instructor: {
            name: "Prof. Ramesh Gupta",
            image: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
            rating: 4.6,
        },
        pricing: {
            current: 1499,
            original: 2499,
            discount: 40,
        },
        stats: {
            students: 15600,
            rating: 4.6,
            reviews: 4200,
            accuracy: 93,
        },
        features: ["Board Pattern", "Sample Papers", "Marking Scheme", "Time Management"],
        badge: "Foundation",
        isNew: false,
        isFree: false,
        testTypes: ["Full Length", "Subject Wise", "Sample Papers"],
    },
    {
        id: 6,
        title: "Free Programming Quiz Series",
        description: "Test your programming knowledge with free quizzes on various programming languages",
        image: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=2940&auto=format&fit=crop",
        category: "Programming",
        subcategory: "General",
        level: "Beginner",
        totalTests: 15,
        duration: "30 minutes per test",
        language: "English",
        instructor: {
            name: "Prof. Sarah Johnson",
            image: "https://images.unsplash.com/photo-1494790108755-2616b612b786?q=80&w=2940&auto=format&fit=crop",
            rating: 4.4,
        },
        pricing: {
            current: 0,
            original: 0,
            discount: 0,
        },
        stats: {
            students: 25000,
            rating: 4.4,
            reviews: 6500,
            accuracy: 88,
        },
        features: ["Multiple Languages", "Instant Results", "Skill Assessment", "Certificate"],
        badge: "Free",
        isNew: false,
        isFree: true,
        testTypes: ["Skill Based", "Language Specific", "General"],
    },
];

export const testFilterOptions = {
    categories: ["All", "GATE", "IAS", "JEE", "NEET", "Class 12", "Programming"],
    subcategories: {
        GATE: ["Mechanical", "Computer Science", "Electrical", "Civil"],
        IAS: ["Prelims", "Mains", "Interview"],
        JEE: ["Main", "Advanced"],
        NEET: ["Medical"],
        "Class 12": ["Board Exams", "Competitive Prep"],
        Programming: ["General", "Language Specific"],
    },
    levels: ["All", "Beginner", "Intermediate", "Advanced"],
    languages: ["All", "English", "Hindi"],
    pricing: ["All", "Free", "Paid", "Under ₹2,000", "₹2,000 - ₹4,000", "Above ₹4,000"],
    testTypes: ["All", "Full Length", "Subject Wise", "Chapter Wise", "Previous Year"],
};

export const testSortOptions = [
    { value: "popularity", label: "Most Popular" },
    { value: "rating", label: "Highest Rated" },
    { value: "price-low", label: "Price: Low to High" },
    { value: "price-high", label: "Price: High to Low" },
    { value: "newest", label: "Newest First" },
    { value: "tests", label: "Most Tests" },
];
